"""Initial tenant-isolated platform schema.
Revision ID: 0001
"""
from alembic import op
revision="0001"; down_revision=None; branch_labels=None; depends_on=None

def upgrade():
 op.execute('CREATE EXTENSION IF NOT EXISTS vector')
 op.execute('CREATE EXTENSION IF NOT EXISTS pgcrypto')
 op.execute('CREATE EXTENSION IF NOT EXISTS btree_gist')
 op.execute('''CREATE TYPE pipeline_stage AS ENUM ('NEW_LEAD','QUALIFIED','APPOINTMENT_BOOKED','SECURITY_REVIEW','PROPOSAL','NEGOTIATION','WON','LOST');
 CREATE TYPE approval_status AS ENUM ('PENDING','APPROVED','REJECTED','EXPIRED','EXECUTED');
 CREATE TABLE tenants(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, slug text UNIQUE NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz);
 CREATE TABLE users(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id), external_subject text NOT NULL, email_ciphertext bytea, mfa_enforced boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz, UNIQUE(tenant_id,external_subject));
 CREATE TABLE roles(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid REFERENCES tenants(id), name text NOT NULL, UNIQUE(tenant_id,name));
 CREATE TABLE permissions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text UNIQUE NOT NULL);
 CREATE TABLE role_permissions(role_id uuid REFERENCES roles(id) ON DELETE CASCADE, permission_id uuid REFERENCES permissions(id) ON DELETE CASCADE, PRIMARY KEY(role_id,permission_id));
 CREATE TABLE user_roles(user_id uuid REFERENCES users(id) ON DELETE CASCADE, role_id uuid REFERENCES roles(id) ON DELETE CASCADE, PRIMARY KEY(user_id,role_id));
 CREATE TABLE companies(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id), name text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz);
 CREATE TABLE contacts(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id), company_id uuid REFERENCES companies(id), name text NOT NULL, email_ciphertext bytea, phone_ciphertext bytea, consent jsonb NOT NULL DEFAULT '{}', communication_preferences jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz);
 CREATE TABLE opportunities(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id), contact_id uuid REFERENCES contacts(id), company_id uuid REFERENCES companies(id), stage pipeline_stage NOT NULL DEFAULT 'NEW_LEAD', lead_owner uuid REFERENCES users(id), estimated_value numeric(14,2), source text, next_action text, last_interaction timestamptz, created_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz);
 CREATE TABLE crm_activities(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id), opportunity_id uuid REFERENCES opportunities(id), actor_id uuid, activity_type text NOT NULL, notes text, occurred_at timestamptz NOT NULL DEFAULT now());
 CREATE TABLE appointments(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id), opportunity_id uuid REFERENCES opportunities(id), contact_id uuid REFERENCES contacts(id), provider text NOT NULL, external_event_id text, starts_at timestamptz NOT NULL, ends_at timestamptz NOT NULL, timezone text NOT NULL, status text NOT NULL, idempotency_key text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,idempotency_key), EXCLUDE USING gist (tenant_id WITH =, tstzrange(starts_at,ends_at) WITH &&) WHERE (status IN ('BOOKED','CONFIRMED')));
 CREATE TABLE conversations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id), contact_id uuid REFERENCES contacts(id), channel text NOT NULL, external_id text, summary text, escalated boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,channel,external_id));
 CREATE TABLE messages(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id), conversation_id uuid NOT NULL REFERENCES conversations(id), external_message_id text, direction text NOT NULL, content text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,external_message_id));
 CREATE TABLE knowledge_documents(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id), title text NOT NULL, content text NOT NULL, category text NOT NULL, source text NOT NULL, visibility text NOT NULL, version integer NOT NULL, status text NOT NULL DEFAULT 'DRAFT', approved_by uuid REFERENCES users(id), effective_date timestamptz, review_at timestamptz, expires_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz);
 CREATE TABLE knowledge_chunks(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id), document_id uuid NOT NULL REFERENCES knowledge_documents(id) ON DELETE CASCADE, content text NOT NULL, embedding vector(1536), created_at timestamptz NOT NULL DEFAULT now());
 CREATE INDEX knowledge_chunks_embedding_hnsw ON knowledge_chunks USING hnsw (embedding vector_cosine_ops);
 CREATE TABLE integrations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id), kind text NOT NULL, secret_reference text NOT NULL, config_redacted jsonb NOT NULL DEFAULT '{}', enabled boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now());
 CREATE TABLE assets(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id), name text NOT NULL, canonical_target text NOT NULL, allowlisted boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz, UNIQUE(tenant_id,canonical_target));
 CREATE TABLE asset_verifications(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id), asset_id uuid NOT NULL REFERENCES assets(id), method text NOT NULL, verified_at timestamptz, expires_at timestamptz, evidence_reference text);
 CREATE TABLE security_events(id uuid PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), asset_id uuid NOT NULL REFERENCES assets(id), source text NOT NULL, event_type text NOT NULL, severity smallint NOT NULL CHECK(severity BETWEEN 0 AND 10), confidence numeric(4,3) NOT NULL, occurred_at timestamptz NOT NULL, src_ip inet, destination text, request_path text, user_reference text, country text, user_agent text, signature text, rule_id text, metadata_redacted jsonb NOT NULL DEFAULT '{}', raw_event_reference text, created_at timestamptz NOT NULL DEFAULT now());
 CREATE TABLE incidents(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id), title text NOT NULL, risk text NOT NULL, claim text NOT NULL DEFAULT 'SUSPECTED INCIDENT', status text NOT NULL DEFAULT 'OPEN', confirmed_by uuid REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
 CREATE TABLE incident_events(tenant_id uuid NOT NULL REFERENCES tenants(id), incident_id uuid REFERENCES incidents(id) ON DELETE CASCADE, event_id uuid REFERENCES security_events(id), PRIMARY KEY(incident_id,event_id));
 CREATE TABLE approval_requests(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id), action_type text NOT NULL, requested_by uuid NOT NULL, requested_at timestamptz NOT NULL DEFAULT now(), payload_hash char(64) NOT NULL, reason text NOT NULL, risk_level text NOT NULL, expires_at timestamptz NOT NULL, status approval_status NOT NULL DEFAULT 'PENDING', approved_by uuid REFERENCES users(id), approved_at timestamptz);
 CREATE TABLE scan_jobs(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id), asset_id uuid NOT NULL REFERENCES assets(id), approval_id uuid NOT NULL REFERENCES approval_requests(id), authorization_ticket text NOT NULL, profile text NOT NULL CHECK(profile IN ('safe-passive','safe-standard')), status text NOT NULL DEFAULT 'QUEUED', idempotency_key text NOT NULL, scheduled_at timestamptz, started_at timestamptz, finished_at timestamptz, UNIQUE(tenant_id,idempotency_key));
 CREATE TABLE findings(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id), scan_job_id uuid REFERENCES scan_jobs(id), asset_id uuid NOT NULL REFERENCES assets(id), scanner text NOT NULL, title text NOT NULL, severity text NOT NULL, evidence_redacted jsonb NOT NULL DEFAULT '{}', false_positive_status text NOT NULL DEFAULT 'UNREVIEWED', remediation_status text NOT NULL DEFAULT 'OPEN', created_at timestamptz NOT NULL DEFAULT now());
 CREATE TABLE malware_results(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id), asset_id uuid REFERENCES assets(id), sha256 char(64) NOT NULL, mime_type text NOT NULL, size_bytes bigint NOT NULL, clamav_result text, yara_matches jsonb NOT NULL DEFAULT '[]', quarantine_status text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
 CREATE TABLE waf_actions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id), approval_id uuid REFERENCES approval_requests(id), action_type text NOT NULL, payload_hash char(64) NOT NULL, expires_at timestamptz, status text NOT NULL DEFAULT 'RECOMMENDED', created_at timestamptz NOT NULL DEFAULT now());
 CREATE TABLE notifications(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id), channel text NOT NULL, recipient_reference text NOT NULL, template text NOT NULL, status text NOT NULL DEFAULT 'QUEUED', created_at timestamptz NOT NULL DEFAULT now());
 CREATE TABLE agent_runs(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id), agent_name text NOT NULL CHECK(agent_name IN ('SAMIIR','FATMA')), actor_id text NOT NULL, trace_id text, started_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz);
 CREATE TABLE tool_calls(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id), agent_run_id uuid NOT NULL REFERENCES agent_runs(id), tool_name text NOT NULL, arguments_hash char(64) NOT NULL, authorization_result text NOT NULL, latency_ms integer, created_at timestamptz NOT NULL DEFAULT now());
 CREATE TABLE audit_logs(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id), actor_type text NOT NULL, actor_id text NOT NULL, agent_name text, agent_run_id uuid REFERENCES agent_runs(id), tool_name text, action text NOT NULL, target_type text, target_id uuid, request_id text NOT NULL, source_ip inet, result text NOT NULL, risk_level text, approval_id uuid REFERENCES approval_requests(id), metadata_redacted jsonb NOT NULL DEFAULT '{}', previous_hash char(64), entry_hash char(64) NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
 CREATE INDEX security_events_tenant_time ON security_events(tenant_id,occurred_at DESC); CREATE INDEX incidents_tenant_status ON incidents(tenant_id,status); CREATE INDEX audit_tenant_time ON audit_logs(tenant_id,created_at DESC);
 ''')
 for table in ['users','companies','contacts','opportunities','crm_activities','appointments','conversations','messages','knowledge_documents','knowledge_chunks','integrations','assets','asset_verifications','security_events','incidents','incident_events','approval_requests','scan_jobs','findings','malware_results','waf_actions','notifications','agent_runs','tool_calls','audit_logs']:
  op.execute(f'ALTER TABLE {table} ENABLE ROW LEVEL SECURITY')
  op.execute(f"CREATE POLICY tenant_isolation ON {table} USING (tenant_id = nullif(current_setting('app.tenant_id', true),'')::uuid) WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true),'')::uuid)")

def downgrade():
 for table in reversed(['audit_logs','tool_calls','agent_runs','notifications','waf_actions','malware_results','findings','scan_jobs','approval_requests','incident_events','incidents','security_events','asset_verifications','assets','integrations','knowledge_chunks','knowledge_documents','messages','conversations','appointments','crm_activities','opportunities','contacts','companies','user_roles','role_permissions','permissions','roles','users','tenants']): op.execute(f'DROP TABLE IF EXISTS {table} CASCADE')
 op.execute('DROP TYPE IF EXISTS approval_status; DROP TYPE IF EXISTS pipeline_stage')
